language: ruby
rvm:
  - 2.3.1

before_install: gem install bundler # update bundler.
script: script/cibuild
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false

deploy:
  gem: don-pages
  provider: rubygems
  api_key: $RUBYGEMS_KEY
  on:
    tags: true

after_deploy: curl -s -X POST $DOCKER_TRIGGER_URL

cache: bundler
sudo: false
